import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import { NextUIProvider } from "@nextui-org/react"
import { ThemeProvider } from "@/components/ThemeProvider"
import { ModeToggle } from "@/components/ToggleTheme"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} `}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<NextUIProvider>
						<div className="">{children}</div>
					</NextUIProvider>
				</ThemeProvider>
			</body>
			<Toaster />
		</html>
	)
}
